theme: jekyll-theme-leap-day
title: Welcome to Maria's Page!
description: Hi Reader! My name is Maria Fedirko, and I am a sophomore at UIUC studying applied mathematics. I am very interested in Statistics and Combinatorics. 
